---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
    checks:
      Identical code:
        enabled: false
      Naming/ShortVariable:
        enabled: false
  fixme:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
  - "**.php"
exclude_paths:
- tests/
